CREATE TABLE IF NOT EXISTS login(
    id INT PRIMARY KEY AUTO_INCREMENT,
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    token TEXT NOT NULL, 
    expire_at TIMESTAMP NOT NULL,
    deleted ENUM('Y','N') DEFAULT 'N',
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);